<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.6" xml:lang="en-US">
  <compounddef id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest" kind="class" language="Python" prot="public">
    <compoundname>googletest-throw-on-failure-test::ThrowOnFailureTest</compoundname>
    <basecompoundref prot="public" virt="non-virtual">gtest_test_utils.TestCase</basecompoundref>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1ac9966623ba3bbd94be99aef689db43f3" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify</definition>
        <argsstring>(self, env_var_value, flag_value, should_fail)</argsstring>
        <name>RunAndVerify</name>
        <qualifiedname>googletest-throw-on-failure-test.ThrowOnFailureTest.RunAndVerify</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>env_var_value</type>
          <defname>env_var_value</defname>
        </param>
        <param>
          <type>flag_value</type>
          <defname>flag_value</defname>
        </param>
        <param>
          <type>should_fail</type>
          <defname>should_fail</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Runs googletest-throw-on-failure-test_ and verifies its behavior.

Runs googletest-throw-on-failure-test_ and verifies that it does
(or does not) exit with a non-zero code.

Args:
  env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
    variable; None if the variable should be unset.
  flag_value:       value of the --gtest_break_on_failure flag; None if the
    flag should not be present.
  should_fail:      True if and only if the program is expected to fail.
</verbatim> </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="87" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="87" bodyend="138"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a55494f56e9674d086077e82583e8f823" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def googletest-throw-on-failure-test.ThrowOnFailureTest.testDefaultBehavior</definition>
        <argsstring>(self)</argsstring>
        <name>testDefaultBehavior</name>
        <qualifiedname>googletest-throw-on-failure-test.ThrowOnFailureTest.testDefaultBehavior</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Tests the behavior of the default mode.</verbatim> </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="139" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="139" bodyend="143"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a8ab58ce03ffb9fa474a6c9282bb13021" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureEnvVar</definition>
        <argsstring>(self)</argsstring>
        <name>testThrowOnFailureEnvVar</name>
        <qualifiedname>googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureEnvVar</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Tests using the GTEST_THROW_ON_FAILURE environment variable.</verbatim> </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="144" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="144" bodyend="149"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1aeded6eb7d9c7e95f4d18768c4a767eaf" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureFlag</definition>
        <argsstring>(self)</argsstring>
        <name>testThrowOnFailureFlag</name>
        <qualifiedname>googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureFlag</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Tests using the --gtest_throw_on_failure flag.</verbatim> </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="150" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="150" bodyend="155"/>
      </memberdef>
      <memberdef kind="function" id="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a18515553dbfe7b3e6ed6449fa81893c1" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar</definition>
        <argsstring>(self)</argsstring>
        <name>testThrowOnFailureFlagOverridesEnvVar</name>
        <qualifiedname>googletest-throw-on-failure-test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar</qualifiedname>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Tests that --gtest_throw_on_failure overrides GTEST_THROW_ON_FAILURE.</verbatim> </para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="156" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="156" bodyend="164"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Tests the throw-on-failure mode.</verbatim> </para>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>googletest-throw-on-failure-test.ThrowOnFailureTest</label>
        <link refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>gtest_test_utils.TestCase</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>googletest-throw-on-failure-test.ThrowOnFailureTest</label>
        <link refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>gtest_test_utils.TestCase</label>
      </node>
    </collaborationgraph>
    <location file="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" line="84" column="1" bodyfile="build/_deps/googletest-src/googletest/test/googletest-throw-on-failure-test.py" bodystart="84" bodyend="164"/>
    <listofallmembers>
      <member refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1ac9966623ba3bbd94be99aef689db43f3" prot="public" virt="non-virtual"><scope>googletest-throw-on-failure-test::ThrowOnFailureTest</scope><name>RunAndVerify</name></member>
      <member refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a55494f56e9674d086077e82583e8f823" prot="public" virt="non-virtual"><scope>googletest-throw-on-failure-test::ThrowOnFailureTest</scope><name>testDefaultBehavior</name></member>
      <member refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a8ab58ce03ffb9fa474a6c9282bb13021" prot="public" virt="non-virtual"><scope>googletest-throw-on-failure-test::ThrowOnFailureTest</scope><name>testThrowOnFailureEnvVar</name></member>
      <member refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1aeded6eb7d9c7e95f4d18768c4a767eaf" prot="public" virt="non-virtual"><scope>googletest-throw-on-failure-test::ThrowOnFailureTest</scope><name>testThrowOnFailureFlag</name></member>
      <member refid="classgoogletest-throw-on-failure-test_1_1ThrowOnFailureTest_1a18515553dbfe7b3e6ed6449fa81893c1" prot="public" virt="non-virtual"><scope>googletest-throw-on-failure-test::ThrowOnFailureTest</scope><name>testThrowOnFailureFlagOverridesEnvVar</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
